---
- hosts: localhost

  tasks:
  - name: create docker image for our Web Page using webpage.war file (artifact)
    command: docker build -t serhiikalchenko/webpage-image .
    args:
      chdir: /opt/docker

  - name: push image to Docker Hub
    command: docker push serhiikalchenko/webpage-image

  - name: remove docker images from Ansible-Server
    command: docker rmi serhiikalchenko/webpage-image
    ignore_errors: yes
