---
- hosts: webservers

  tasks:
  - name: remove docker container (if it's running)
    command: docker rm -f webpage
    ignore_errors: yes

  - name: remove current docker image (if it's available) 
    command: docker rmi serhiikalchenko/webpage-image
    ignore_errors: yes

  - name: pull new image from Docker Hub
    command: docker pull serhiikalchenko/webpage-image

  - name: launch docker container from our new image
    command: docker run -d --name webpage -p 8080:8080 serhiikalchenko/webpage-image


